version: '3.3'
services:
  backend:
    image: aminhelloworld/medtrackr-be:${IMAGE_TAG}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_PORT=${NODE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DB=${DB_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}